import type { Authorship } from "@/lib/posts";

interface AuthorshipBadgeProps {
	authorship: Authorship;
	className?: string;
}

function CheckIcon() {
	return (
		<svg
			viewBox="0 0 16 16"
			width="14"
			height="14"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
			aria-hidden="true"
		>
			<path d="M13.25 4.75 6 12 2.75 8.75" />
		</svg>
	);
}

function SparkleIcon() {
	return (
		<svg
			viewBox="0 0 16 16"
			width="14"
			height="14"
			fill="currentColor"
			aria-hidden="true"
		>
			<path d="M8 0c.2 2.5 1.5 5 4 5.5-2.5.5-3.8 3-4 5.5-.2-2.5-1.5-5-4-5.5C6.5 5 7.8 2.5 8 0Z" />
			<path d="M12.5 8c.1 1.2.8 2.4 2 2.6-1.2.2-1.9 1.4-2 2.6-.1-1.2-.8-2.4-2-2.6 1.2-.2 1.9-1.4 2-2.6Z" opacity=".6" />
		</svg>
	);
}

export function AuthorshipBadge({ authorship, className }: AuthorshipBadgeProps) {
	const isHuman = authorship === "human";
	const isDraft = authorship === "draft";

	return (
		<span
			className={`authorship-badge ${isHuman ? "authorship-badge--human" : "authorship-badge--ai"} ${className ?? ""}`}
			title={
				isHuman
					? "Written by a human"
					: isDraft
						? "Not human-verified; treat as an AI draft"
						: "Generated by AI"
			}
		>
			{isHuman ? <CheckIcon /> : <SparkleIcon />}
			{isHuman ? "Verified Human" : isDraft ? "AI Draft" : "AI Generated"}
		</span>
	);
}
